[package]
name = "hi-tui"
description = "Terminal UI built on ratatui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
ratatui.workspace = true
crossterm.workspace = true
serde_json.workspace = true
unicode-width = "0.2"

hi-core = { workspace = true }
